[default.publisher.telegram]
active=true
chat_id="xxx"
token="xxx"
username="xxx"
[default.publisher.zulip]
active=true
instance="xxx"
chat_id="xxx"
subject="xxx"
bot_token="xxx"
bot_email="xxx"
[default.publisher.twitter]
active=true
api_key="xxx"
api_key_secret="xxx"
access_token="xxx"
access_secret="xxx"
[default.publisher.mastodon]
active=true
instance="xxx"
token="xxx"
name="xxx"
toot_length=500

[default.publisher.facebook]

active=true
page_access_token="xxx"

[default.notifier.telegram]
active=true
chat_id="xxx"
token="xxx"
username="xxx"
[default.notifier.zulip]
active=true
instance="xxx"
chat_id="xxx"
subject="xxx"
bot_token="xxx"
bot_email="xxx"
[default.notifier.twitter]
active=true
api_key="xxx"
api_key_secret="xxx"
access_token="xxx"
access_secret="xxx"
[default.notifier.mastodon]
active=false

[default.notifier.facebook]
active=false
page_access_token="xxx"